/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ahmov;

/**
 *
 * @author Armando
 */
public class Menú extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public Menú() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        BtnAgenda = new javax.swing.JButton();
        BtnAgenda1 = new javax.swing.JButton();
        BtnAgenda2 = new javax.swing.JButton();
        BtnAgenda3 = new javax.swing.JButton();
        BtnFacturar = new javax.swing.JButton();
        BtnAgenda5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        getContentPane().add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(350, 589));

        BtnAgenda.setBackground(new java.awt.Color(102, 102, 102));
        BtnAgenda.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        BtnAgenda.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgenda.setText("Administrar Usuarios");
        BtnAgenda.setBorder(null);
        BtnAgenda.setBorderPainted(false);
        BtnAgenda.setContentAreaFilled(false);
        BtnAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgenda.setIconTextGap(0);
        BtnAgenda.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgendaActionPerformed(evt);
            }
        });

        BtnAgenda1.setBackground(new java.awt.Color(102, 102, 102));
        BtnAgenda1.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        BtnAgenda1.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgenda1.setText("Mantenimiento");
        BtnAgenda1.setBorder(null);
        BtnAgenda1.setBorderPainted(false);
        BtnAgenda1.setContentAreaFilled(false);
        BtnAgenda1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgenda1.setIconTextGap(0);
        BtnAgenda1.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnAgenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgenda1ActionPerformed(evt);
            }
        });

        BtnAgenda2.setBackground(new java.awt.Color(102, 102, 102));
        BtnAgenda2.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        BtnAgenda2.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgenda2.setText("Administrar Clientes");
        BtnAgenda2.setBorder(null);
        BtnAgenda2.setBorderPainted(false);
        BtnAgenda2.setContentAreaFilled(false);
        BtnAgenda2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgenda2.setIconTextGap(0);
        BtnAgenda2.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnAgenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgenda2ActionPerformed(evt);
            }
        });

        BtnAgenda3.setBackground(new java.awt.Color(102, 102, 102));
        BtnAgenda3.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        BtnAgenda3.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgenda3.setText("Reportes Administrativos");
        BtnAgenda3.setBorder(null);
        BtnAgenda3.setBorderPainted(false);
        BtnAgenda3.setContentAreaFilled(false);
        BtnAgenda3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgenda3.setIconTextGap(0);
        BtnAgenda3.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnAgenda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgenda3ActionPerformed(evt);
            }
        });

        BtnFacturar.setBackground(new java.awt.Color(102, 102, 102));
        BtnFacturar.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        BtnFacturar.setForeground(new java.awt.Color(255, 255, 255));
        BtnFacturar.setText("Facturar");
        BtnFacturar.setBorder(null);
        BtnFacturar.setBorderPainted(false);
        BtnFacturar.setContentAreaFilled(false);
        BtnFacturar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnFacturar.setIconTextGap(0);
        BtnFacturar.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFacturarActionPerformed(evt);
            }
        });

        BtnAgenda5.setBackground(new java.awt.Color(102, 102, 102));
        BtnAgenda5.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 1, 14)); // NOI18N
        BtnAgenda5.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgenda5.setText(" Agendar Cita");
        BtnAgenda5.setBorder(null);
        BtnAgenda5.setBorderPainted(false);
        BtnAgenda5.setContentAreaFilled(false);
        BtnAgenda5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAgenda5.setIconTextGap(0);
        BtnAgenda5.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnAgenda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgenda5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnAgenda3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAgenda2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(BtnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(BtnAgenda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAgenda5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(BtnAgenda5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgenda1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgenda3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgendaActionPerformed
        PanelUsuarios p1 = new PanelUsuarios();
        p1.setSize(PanelPrincipal.getSize());
        PanelPrincipal.add(p1);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_BtnAgendaActionPerformed

    private void BtnAgenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgenda1ActionPerformed
        PanelMantenimiento p1 = new PanelMantenimiento();
        p1.setSize(PanelPrincipal.getSize());
        PanelPrincipal.add(p1);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_BtnAgenda1ActionPerformed

    private void BtnAgenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgenda2ActionPerformed
        PanelCliente p1 = new PanelCliente();
        p1.setSize(PanelPrincipal.getSize());
        PanelPrincipal.add(p1);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_BtnAgenda2ActionPerformed

    private void BtnAgenda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgenda3ActionPerformed
        PanelReporte p1 = new PanelReporte();
        p1.setSize(PanelPrincipal.getSize());
        PanelPrincipal.add(p1);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_BtnAgenda3ActionPerformed

    private void BtnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFacturarActionPerformed
        PanelFacturar p1 = new PanelFacturar();
        p1.setSize(PanelPrincipal.getSize());
        PanelPrincipal.add(p1);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();    }//GEN-LAST:event_BtnFacturarActionPerformed

    private void BtnAgenda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgenda5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgenda5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menú().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgenda;
    private javax.swing.JButton BtnAgenda1;
    private javax.swing.JButton BtnAgenda2;
    private javax.swing.JButton BtnAgenda3;
    private javax.swing.JButton BtnAgenda5;
    private javax.swing.JButton BtnFacturar;
    private javax.swing.JPanel PanelPrincipal;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
