/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ahmov;

/**
 *
 * @author USUARIO
 */
public class PanelMantenimiento extends javax.swing.JPanel {

    /**
     * Creates new form PanelMantenimiento
     */
    public PanelMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCitas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblAgenda = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtAgenda = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        cmbEstado = new javax.swing.JComboBox<>();
        lblDetalle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDetalle = new javax.swing.JTextArea();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();

        Panel1.setBackground(new java.awt.Color(204, 204, 255));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(102, 102, 255));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        Panel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        btnEditar.setBackground(new java.awt.Color(102, 102, 255));
        btnEditar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        Panel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        Panel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, -1, -1));

        btnRefrescar.setBackground(new java.awt.Color(102, 102, 255));
        btnRefrescar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        btnRefrescar.setText("Refrescar");
        Panel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, -1, -1));

        tbCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCitas);

        Panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 860, 260));

        jLabel1.setFont(new java.awt.Font("hello honey - Personal Use", 2, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setText("Mantenimiento");
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 400, -1));

        lblAgenda.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblAgenda.setForeground(new java.awt.Color(102, 51, 255));
        lblAgenda.setText("Agenda de Cita:");
        Panel1.add(lblAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        lblFecha.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(102, 51, 255));
        lblFecha.setText("Fecha Estimada:");
        Panel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        Panel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 160, -1));

        lblEstado.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(102, 51, 255));
        lblEstado.setText("Estado de Cita:");
        Panel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));
        Panel1.add(txtAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 160, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        Panel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(14, 24));
        Panel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 160, -1));

        lblDetalle.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDetalle.setForeground(new java.awt.Color(102, 51, 255));
        lblDetalle.setText("Detalle de cita:");
        Panel1.add(lblDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        taDetalle.setLineWrap(true);
        taDetalle.setRows(5);
        taDetalle.setAutoscrolls(false);
        jScrollPane2.setViewportView(taDetalle);

        Panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 360, -1));

        lblPrecio.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(102, 51, 255));
        lblPrecio.setText("Precio Estimado:");
        Panel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));
        Panel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextArea taDetalle;
    private javax.swing.JTable tbCitas;
    private javax.swing.JTextField txtAgenda;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
